config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  root "products#index"
  get 'top/about' => 'top#about'
  get "users/delete" => "users#delete", as: "users_delete"
  resources :users, only: [:show, :index, :edit, :update, :destroy]

  namespace :admin do
    get 'top'=>'orders#top'
    resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :users,only: [:index, :show, :edit, :update]
    resources :orders,only: [:index, :show]
    resources :order_details,only: [:update]
    resources :categories,only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_scope :user do
    get 'users/sign_up/done', to: 'users/registrations#done'
    post 'user/cart_items' => "user/cart_items#create"
    delete 'user/cart_item/:id' => "user/cart_items#destroy", as: "cart_item"
    patch 'user/cart_item/:id' => "user/cart_items#update"
    put 'user/cart_item/:id' => "user/cart_items#update"
    get 'cart_items/confirm' => "user/cart_items#confirm"
    delete 'cart_items/destroy_all' => "user/cart_items#destroy_all", as: "cart_items_destroy_all"
    get 'new/user/order' => "user/orders#new"
    get 'user/orders/:id' => "user/orders#show", as: "order_show"
    get 'user/orders' => "user/orders#index"
    post 'user/orders' => "user/orders#create", as: "order_create"
    get 'orders/complete' => "user/orders#complete"
    post 'orders/confirm' => "user/orders#confirm"
    resources :products, only: [:show]
    resources :shippings
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_details, dependent: :destroy

	enum payment_method: { 銀行振込: false, クレジットカード: true }
    enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	def top
      now = Time.current
      @orders = Order.where(created_at: now.all_day)
	end

	def index
      @orders = Order.all.order(id: "DESC")
	end

	def show
	  @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
	end

	def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(params[:order_id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
      # 注文ステータスの変更で、それぞれの制作ステータスを変更
      @order_details.each do |order_detail|
        order_detail.update(work_status: "制作待ち")
      end
    end
    redirect_to admin_order_path(@order)
  end

	private

	def order_params
      params.require(:order).permit(:order_status)
    end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController

  def index
    @orders = Order.where(user_id: current_user.id).order(id: "DESC")
  end

  def new
  	@order = Order.new
    @user_address = Shipping.where(user_id: current_user.id)
    @user = current_user
  end

  def create
    @order = Order.new(order_params) # 新規でオーダーのパラメーター受けとるための
    @order.user_id = current_user.id # オーダーとユーザーの紐付け
    if @order.save
      cart_items = current_user.cart_items # カートアイテムを全取得
      cart_items.each do |cart_item|
        order_detail = @order.order_details.new # 履歴の空を作成、オーダーと履歴紐付け
        order_detail.product_id = cart_item.product_id # カートの商品を取得
        order_detail.count = cart_item.count
        order_detail.price = cart_item.product.price
        order_detail.save  # 注文履歴をセーブ
        cart_item.destroy  # カート内アイテムを空に削除
      end
      redirect_to orders_complete_path
    else
      redirect_to new_user_order_path
    end
  end

  def complete
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def confirm
    @order_products = current_user.cart_items.all # オーダーされた商品とユーザーのカート内商品紐付け
    @order = Order.new # ステータス受けとるための空を作成
    @order.payment_method = params[:payment_method]
    if params[:addresses] == "1" # from_withで定義している
      @order.postcode = current_user.postcode
      @order.prefecture_code = current_user.prefecture_code
      @order.address_city = current_user.address_city
      @order.address_street = current_user.address_street
      @order.address_building = current_user.address_building
      @order.name = current_user.last_name + current_user.first_name

    elsif params[:addresses] == "2"
      @shipping = Shipping.find(params[:select_address])
      @order.postcode = @shipping.postcode
      @order.prefecture_code = @shipping.prefecture_code
      @order.address_city = @shipping.address_city
      @order.address_street = @shipping.address_street
      @order.address_building = @shipping.address_building
      @order.name = @shipping.name

    else params[:addresses] == "3"
         @shipping = Shipping.new # 住所新規登録するためのnew
         # 3を選ばれた際、送られたパラメーターを各カラムで受けとる
         @order.postcode = params[:postcode]
         @order.prefecture_code = params[:prefecture_code]
         @order.address_city = params[:address_city]
         @order.address_street = params[:address_street]
         @order.address_building = params[:address_building]
         @order.name = params[:name]

         # オーダーモデルに渡されたパラメーターをshippingモデルに渡す
         @shipping.user_id = current_user.id # ユーザーの紐付け
         @shipping.postcode = @order.postcode
         @shipping.prefecture_code = @order.prefecture_code
         @shipping.address_city = @order.address_city
         @shipping.address_street = @order.address_street
         @shipping.address_building = @order.address_building
         @shipping.name = @order.name
         @shipping.save
    end
  end

  private

  def order_params
    params.permit(:user_id, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :name, :postage, :total_price, :payment_method, :order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/views/admin/orders/index.html.haml
=render "template/header_admin"
.top-index
  .container
    .row
      .col-lg-8.offset-lg-2
        %h3.page-title
          注文履歴一覧
        %table.table
          %thead.thead-light
            %tr
              %th 購入日時
              %th 購入者
              %th 注文個数
              %th 注文ステータス
          - @orders.each do |order|
            %tr
              %td
                = link_to admin_order_path(order) do
                  %span
                    = order.created_at.strftime('%Y/%m/%d %H:%M:%S')
              %td
                = order.user.first_name
                = order.user.last_name
              %td
                - @sum = 0
                - order.order_details.each do |order_detail|
                  - @sum += order_detail.count.to_i
                  = @sum
              %td= order.order_status
              

app/views/admin/orders/show.html.haml
=render "template/header_admin"
.order-show
  .row
    .col-xs-9
      %h3.page-title
        注文履歴詳細
      .field
        .col-xs-3
          %b 購入者
        .col-xs-8
          = @order.name
      .field
        .col-xs-3
          %b 配送先
        .col-xs-8
          = @order.postcode
          = @order.prefecture_code
          = @order.address_city
          = @order.address_street
          = @order.address_building
      .field
        .col-xs-3
          %b 支払い方法
        .col-xs-8
          = @order.payment_method
      = form_for(@order, url: admin_order_path, method: :patch) do |f|
        .col-xs-3 
          %b 注文ステータス
        .col-xs-6
          = f.select :order_status, Order.order_statuses.keys, class: "order_status"
        .actions
          .col-xs-2= f.submit '更新'  ,class: "btn btn-warning"
    .buyer-order.col-xs-9
      %table.table.table-hover.table-bordered.table-inverse
        %thead
          %tr.info
            %th.col-xs-4 商品名
            %th 単価（税込）
            %th 数量
            %th 小計
            %th 製作ステータス
        %tbody
          - if flash[:notice]
            .flash
              = flash[:notice]
          - @sum = 0
          - @order_details.each do |order_detail|
            %tr
              %td.text-left
                = order_detail.product.name
              %td.text-right
                ¥
                = (order_detail.product.price * 1.1).to_i
              %td.text-right
                = order_detail.count
              %td.text-right
                = (order_detail.product.price * 1.1 * order_detail.count).to_i
                - @sum += (order_detail.product.price * 1.1 * order_detail.count)
              %td.text-right
                = form_for(order_detail ,url: admin_order_detail_path(order_detail),html: {method: "patch"}) do |f|
                  = f.select :work_status, OrderDetail.work_statuses.keys
                  = f.submit "更新", class:"btn btn-warning btn-sm"
    .col-lg-4
      .row
        .col-lg-6>
          %p 商品合計
          %p 送料
          %p 請求金額合計
        .col-lg-6
          %p
            = @sum.to_i
            円
          %p
            = @order.postage
            円
          %p
            = @order.total_price.to_i + @order.postage.to_i
            円

app/views/admin/orders/top.html.haml
=render "template/header_admin"
.admin__top-page
  %p.order-count
    本日の注文件数
    %span
      = link_to admin_orders_path, class: "btn-link" do
        = @orders.count
        件