config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  root "products#index"
  get 'top/about' => 'top#about'
  get "users/delete" => "users#delete", as: "users_delete"
  resources :users, only: [:show, :index, :edit, :update, :destroy]

  namespace :admin do
    get 'top'=>'orders#top'
    resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :users,only: [:index, :show, :edit, :update]
    resources :orders,only: [:index, :show]
    resources :order_details,only: [:update]
    resources :categories,only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_scope :user do
    get 'users/sign_up/done', to: 'users/registrations#done'
    post 'user/cart_items' => "user/cart_items#create"
    delete 'user/cart_item/:id' => "user/cart_items#destroy", as: "cart_item"
    patch 'user/cart_item/:id' => "user/cart_items#update"
    put 'user/cart_item/:id' => "user/cart_items#update"
    get 'cart_items/confirm' => "user/cart_items#confirm"
    delete 'cart_items/destroy_all' => "user/cart_items#destroy_all", as: "cart_items_destroy_all"
    get 'new/user/order' => "user/orders#new"
    get 'user/orders/:id' => "user/orders#show", as: "order_show"
    get 'user/orders' => "user/orders#index"
    post 'user/orders' => "user/orders#create", as: "order_create"
    get 'orders/complete' => "user/orders#complete"
    post 'orders/confirm' => "user/orders#confirm"
    resources :products, only: [:show]
    resources :shippings
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, through: :cart_items, source: :product
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :shippings, dependent: :destroy

  enum is_active: { 退会済: false, 有効: true }
  # 論理削除用の記述 acts_as_paranoidとカラムにdeleted_atを入れることによりデータは残るが削除された扱いになる
  acts_as_paranoid

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	def index
	  @users = User.all.page(params[:page]).per(10)
	end

	def show
	  @user = User.find(params[:id])
	end

	def edit
	  @user = User.find(params[:id])
	end

	def update
	  @user = current_user
	  @user.update(user_params)
	  redirect_to user_path
	end

	private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :phone_number, :email, :password, :is_active)
    end
end

app/controllers/user/cart_items_controller.rb
class User::CartItemsController < ApplicationController
	before_action :authenticate_user!
	def confirm
	  @cart_items = current_user.cart_items
	end

	def update
	  @cart_item = CartItem.find(params[:id])
	  @cart_item.update(cart_item_params)
	  redirect_to cart_items_confirm_path
	end

	def create
	  @cart_item = CartItem.new(cart_item_params)  # ステータス渡す為の空のカート作成
	  @cart_item.user_id = current_user.id # カートのidはユーザーと同じと定義
	  @cart_item.save
      redirect_to cart_items_confirm_path
	end

	def destroy_all
	  CartItem.where(user_id: current_user.id).destroy_all # カートに紐づいてるユーザーのid取得
      redirect_to cart_items_confirm_path
	end

	def destroy
	  @cart_item = CartItem.find(params[:id])
	  @cart_item.destroy
	  redirect_to cart_items_confirm_path
	end

	def cart_item_params # カートに送られるステータス
      params.require(:cart_item).permit(:user_id, :product_id, :count)
    end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController

  def index
    @orders = Order.where(user_id: current_user.id).order(id: "DESC")
  end

  def new
  	@order = Order.new
    @user_address = Shipping.where(user_id: current_user.id)
    @user = current_user
  end

  def create
    @order = Order.new(order_params) # 新規でオーダーのパラメーター受けとるための
    @order.user_id = current_user.id # オーダーとユーザーの紐付け
    if @order.save
      cart_items = current_user.cart_items # カートアイテムを全取得
      cart_items.each do |cart_item|
        order_detail = @order.order_details.new # 履歴の空を作成、オーダーと履歴紐付け
        order_detail.product_id = cart_item.product_id # カートの商品を取得
        order_detail.count = cart_item.count
        order_detail.price = cart_item.product.price
        order_detail.save  # 注文履歴をセーブ
        cart_item.destroy  # カート内アイテムを空に削除
      end
      redirect_to orders_complete_path
    else
      redirect_to new_user_order_path
    end
  end

  def complete
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def confirm
    @order_products = current_user.cart_items.all # オーダーされた商品とユーザーのカート内商品紐付け
    @order = Order.new # ステータス受けとるための空を作成
    @order.payment_method = params[:payment_method]
    if params[:addresses] == "1" # from_withで定義している
      @order.postcode = current_user.postcode
      @order.prefecture_code = current_user.prefecture_code
      @order.address_city = current_user.address_city
      @order.address_street = current_user.address_street
      @order.address_building = current_user.address_building
      @order.name = current_user.last_name + current_user.first_name

    elsif params[:addresses] == "2"
      @shipping = Shipping.find(params[:select_address])
      @order.postcode = @shipping.postcode
      @order.prefecture_code = @shipping.prefecture_code
      @order.address_city = @shipping.address_city
      @order.address_street = @shipping.address_street
      @order.address_building = @shipping.address_building
      @order.name = @shipping.name

    else params[:addresses] == "3"
         @shipping = Shipping.new # 住所新規登録するためのnew
         # 3を選ばれた際、送られたパラメーターを各カラムで受けとる
         @order.postcode = params[:postcode]
         @order.prefecture_code = params[:prefecture_code]
         @order.address_city = params[:address_city]
         @order.address_street = params[:address_street]
         @order.address_building = params[:address_building]
         @order.name = params[:name]

         # オーダーモデルに渡されたパラメーターをshippingモデルに渡す
         @shipping.user_id = current_user.id # ユーザーの紐付け
         @shipping.postcode = @order.postcode
         @shipping.prefecture_code = @order.prefecture_code
         @shipping.address_city = @order.address_city
         @shipping.address_street = @order.address_street
         @shipping.address_building = @order.address_building
         @shipping.name = @order.name
         @shipping.save
    end
  end

  private

  def order_params
    params.permit(:user_id, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :name, :postage, :total_price, :payment_method, :order_status)
  end
end

app/controllers/user/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  	@index_title = "商品"
  	@category = Category.where(is_active: "有効")
  end

  def show
  	@categories = Category.where(is_active: "有効")
  	@product = Product.find(params[:id])
  	@cart_item = CartItem.new
  	@tax_price = (@product.price * 1.1).to_i
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
    def done
      @user = User.new
    end
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
    def after_sign_up_path_for(resource)
      users_sign_up_done_path(resource)
    end

  # The path used after sign up for inactive accounts.
    def after_inactive_sign_up_path_for(resource)
      users_sign_up_done_path(resource)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

  def index
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def delete
    @user = current_user
  end

  def destroy
    @user = current_user
    # 論理削除に合わせて、会員ステータスを退会済に変更させる
    @user.update(is_active: "退会済")
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :password, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :is_active, :phone_number)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/cart_items_helper.rb
module User::CartItemsHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/delete.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
.user__show
  - breadcrumb :delete
  = breadcrumbs pretext: "",separator: " &rsaquo; "
.container
  .row
    .col-lg-12
    %p
      本当に退会しますか？
    %p
      退会すると、会員登録情報や
      %br
        これまでの購入履歴が閲覧できなくなります。
        退会する場合は、「退会する」をクリックしてください。
        %p
          = link_to "退会しない", root_path, class: 'btn btn-warning destroy_book'
          = link_to "Destroy", user_path(@user), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger"

app/views/users/edit.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
.user__show
  - breadcrumb :edit
  = breadcrumbs pretext: "",separator: " &rsaquo; "

.user__edit
  .user__edit__title
    %h2 
      %b アカウント情報編集
  .login-main
    = form_for(@user, url: user_path) do|f|
      .form-group
        = f.label :"お名前　　　　　　"
        = f.text_field :last_name, {placeholder:"例) 八村",class:'form-group__input--half'}
        = f.text_field :first_name, {placeholder:"例) 塁",class: 'form-group__input--half'}
      .form-group
        = f.label :メールアドレス　
        %i.fas.fa-envelope
        = f.email_field :email, {autofocus: true, autocomplete: "email", placeholder: "sample@stores.jp",class: 'form-group__input'}
      .form-group
        = f.label :郵便番号　　　　
        %i.fab.fa-mailchimp
        = f.text_field :postcode,class: 'form-group__input--half'
      .form-group
        = f.label :都道府県　　　　　
        = f.text_field :prefecture_code,class: 'form-group__input'
      .form-group
        = f.label :市区町村　　　　　
        = f.text_field :address_city, {placeholder: "神戸市",class: 'form-group__input',id: "user_address_city"}
      .form-group
        = f.label :番地　　　　　　　
        = f.text_field :address_street, {placeholder: "4-5-6",class: 'form-group__input',id: "user_address_street"}
      .form-group
        = f.label :ビル　　　　　　
        %i.fas.fa-building
        = f.text_field :address_building, {placeholder: "新山麓荘",class: 'form-group__input'}
      .form-group
        = f.label :電話番号　　　　
        %i.fas.fa-phone-alt
        = f.text_field :phone_number, {placeholder: "例) 09012345678",class: 'form-group__input--half'}

      .actions
        = f.submit "変更内容を保存する", class: "btn btn-primary btn-lg btn-block"
        

app/views/users/index.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"

.user__show
  - breadcrumb :index
  = breadcrumbs pretext: "",separator: " &rsaquo; "

  .show__content
    .show__titles
      %b マイページ
    .show__title__subs
      = link_to destroy_user_session_path, method: :delete do
        %b ログアウト
  .show__content
    .show__title
      = link_to user_path(@user), method: :get do
        %b アカウント情報設定
    .show__title__sub
      %p お客様情報の確認・変更ができます　＞
  .show__content
    .show__title
      = link_to shippings_path, method: :get do
        %b 配送先設定
    .show__title__sub
      %p 配送先情報の登録・変更ができます　＞
  .show__content
    .show__title
      = link_to user_orders_path, method: :get do
        %b 購入履歴
    .show__title__sub
      %p 過去の購入履歴が確認できます　＞
  .show__content
    .show__title
      %b お気に入り
    .show__title__sub
      %p お気に入り登録したアイテムが一覧で確認できます　＞
  .show__content
    .show__title
      %b クレジット設定
    .show__title__sub
      %p クレジット情報の登録・変更ができます　＞
  .show__content
    .show__title
      = link_to users_delete_path, method: :get do
        %b 退会する
    .show__title__sub
      %p 
= render "template/footer"

app/views/users/show.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
.user__show
  - breadcrumb :show
  = breadcrumbs pretext: "",separator: " &rsaquo; "
.about
  .row

    .col-lg-12
      %div{:style => "margin-bottom: 20px;"}
        %span{:style => "font-weight: bold; font-size: 20px;"} 登録情報
    .col-lg-5
      %table.table
        %tr
          %td.table-active 氏名
          %td
            = @user.last_name
            = @user.first_name
        %tr
          %td.table-active 郵便番号
          %td= @user.postcode
        %tr
          %td.table-active 都道府県
          %td= @user.prefecture_code
        %tr
          %td.table-active 市区町村
          %td= @user.address_city
        %tr
          %td.table-active 番地
          %td= @user.address_street
        %tr
          %td.table-active ビル
          %td= @user.address_building
        %tr
          %td.table-active 電話番号
          %td= @user.phone_number
        %tr
          %td.table-active メールアドレス
          %td= @user.email
        = link_to "編集する", edit_user_path(@user), data: {"turbolinks" => false}, |
          class:"btn btn-warning", style:"margin-bottom: 10px;"                             |