config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  root "products#index"
  get 'top/about' => 'top#about'
  get "users/delete" => "users#delete", as: "users_delete"
  resources :users, only: [:show, :index, :edit, :update, :destroy]

  namespace :admin do
    get 'top'=>'orders#top'
    resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :users,only: [:index, :show, :edit, :update]
    resources :orders,only: [:index, :show]
    resources :order_details,only: [:update]
    resources :categories,only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_scope :user do
    get 'users/sign_up/done', to: 'users/registrations#done'
    post 'user/cart_items' => "user/cart_items#create"
    delete 'user/cart_item/:id' => "user/cart_items#destroy", as: "cart_item"
    patch 'user/cart_item/:id' => "user/cart_items#update"
    put 'user/cart_item/:id' => "user/cart_items#update"
    get 'cart_items/confirm' => "user/cart_items#confirm"
    delete 'cart_items/destroy_all' => "user/cart_items#destroy_all", as: "cart_items_destroy_all"
    get 'new/user/order' => "user/orders#new"
    get 'user/orders/:id' => "user/orders#show", as: "order_show"
    get 'user/orders' => "user/orders#index"
    post 'user/orders' => "user/orders#create", as: "order_create"
    get 'orders/complete' => "user/orders#complete"
    post 'orders/confirm' => "user/orders#confirm"
    resources :products, only: [:show]
    resources :shippings
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
  def total_price
    @product.price * count
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  enum is_active: { 無効: false, 有効: true }
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_details, dependent: :destroy

	enum payment_method: { 銀行振込: false, クレジットカード: true }
    enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :product
  belongs_to :order
  enum work_status: { 着手不可: 0, 制作待ち: 1, 製作中: 2, 制作完了: 3 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :users, through: :cart_items, source: :users
  has_many :cart_items, dependent: :destroy
  belongs_to :category
  attachment :image

  enum is_active: { 販売停止中: false, 販売中: true }
end

app/models/shipping.rb
class Shipping < ApplicationRecord
	belongs_to :user

    def view_shipping
      postcode
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, through: :cart_items, source: :product
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :shippings, dependent: :destroy

  enum is_active: { 退会済: false, 有効: true }
  # 論理削除用の記述 acts_as_paranoidとカラムにdeleted_atを入れることによりデータは残るが削除された扱いになる
  acts_as_paranoid

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	def index
      @products = Product.all
	end

	def new
      @product = Product.new
	end

	def create
	  @product = Product.new(product_params)

	  if @product.save
        redirect_to admin_products_path(@product)
      else
        render :new
     end
	end

	def show
      @product = Product.find(params[:id])
      @tax_price = (@product.price * 1.1).to_i
	end

	def edit
	  @product = Product.find(params[:id])
	end

	def update
	  @product = Product.find(params[:id])
	  @product.update(product_params)
	  redirect_to admin_products_path
	end

	def destroy
	  @product = Product.find(params[:id])
	  @product.destroy
	  redirect_to admin_products_path
	end
	
	private

	def product_params
      params.require(:product).permit(:name, :introduction, :size, :price, :is_active, :image, :category_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    if user_signed_in?
       root_path(resource)
    else
        admin_top_path
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :phone_number])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  	@index_title = "商品"
  	@category = Category.where(is_active: "有効")
  end

  def show
  	@categories = Category.where(is_active: "有効")
  	@product = Product.find(params[:id])
  	@cart_item = CartItem.new
  	@tax_price = (@product.price * 1.1).to_i
  end

end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController

	def index
	  @shippings = Shipping.where(user_id: current_user.id)
      @shipping = Shipping.new
	end

	def new
	end

	def create
	  @shipping = Shipping.new(shipping_params)
	  @shipping.user_id = current_user.id
	  if @shipping.save
	  	 flash.now[:notice] = "新規配送先を登録しました"
	     redirect_to shippings_path
      end
	end

	def show
	end

	def edit
	  @shipping = Shipping.find(params[:id])
	end

	def update
	  @shipping = Shipping.find(params[:id])
	  @shipping.user_id = current_user.id
	  @shipping.update(shipping_params)
	  redirect_to shippings_path
	end

	def destroy
	  @shipping = Shipping.find(params[:id])
      @shipping.destroy
      redirect_to shippings_path
	end

	private

	def shipping_params
      params.require(:shipping).permit(:user_id, :name, :postcode, :prefecture_code, :address_city, :address_street, :address_building)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	def about
	end
end

app/controllers/user/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  	@index_title = "商品"
  	@category = Category.where(is_active: "有効")
  end

  def show
  	@categories = Category.where(is_active: "有効")
  	@product = Product.find(params[:id])
  	@cart_item = CartItem.new
  	@tax_price = (@product.price * 1.1).to_i
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

  def index
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def delete
    @user = current_user
  end

  def destroy
    @user = current_user
    # 論理削除に合わせて、会員ステータスを退会済に変更させる
    @user.update(is_active: "退会済")
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :password, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :is_active, :phone_number)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def number_to_currency(price)
      "#{price.to_s(:delimited, delimiter: ',')}円"
    end
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user/cart_items_helper.rb
module User::CartItemsHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/edit.html.haml
=render "template/header_admin"
.top-index
  .container
    %h3.page-title
      商品編集
    = form_with(url: admin_product_path, model: @product, method: :patch, local: true) do |f|

      - if @product.errors.any?
        %h3
          = @product.errors.count
          eroor
        %ul
          - @product.errors.full_messages.each do |message|
            %li= message
      .row
        .col-lg-3
          %b 画像のプレビュー
          = f.file_field :image, class: 'img_field', style: 'display:none;'
          = attachment_image_tag @product, :image, fallback: 'no_image.jpg', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev'
        .col-lg-7.offset-lg-1
          .row
            .col-lg-3
              %b 商品名　　
            .col-lg-9
              = f.text_field :name, {autocomplete: "off", class: "product-form"}
          .row
            .col-lg-3
              %b 商品説明　
            .col-lg-9
              = f.text_area :introduction, autocomplete: "off",rows:"8", style:"width:300px",class: "product-introduction-form"
          .row
            .col-lg-3
              %b カテゴリー　
            .col-lg-9
              = f.collection_select :category_id, Category.all,:id, :name, include_blank: "-- 選択してください --"

          .row
            .col-lg-3
              %b 税込価格　
            .col-lg-9
              = f.text_field :price, {autocomplete: "off" , class: "product-form"}
              円
          .row
            .col-lg-3
              %b
                販売
                %br>/
                ステータス
            .col-lg-9
              = f.select :is_active, Product.is_actives.keys, include_blank: "-- 選択してください --"
          .row
            .col-lg-10.offset-lg-1
              = f.submit "変更を保存", class:"btn btn-primary", style:"padding: 10px 30px;"

app/views/admin/products/index.html.haml
=render "template/header_admin"

.top-index
  .container
    .row
      .col-lg-8.offset-lg-2
        %h3.page-title
          商品一覧
        %table.table.table-hover
          %thead.thead-light
            %tr
              %th 商品ID
              %th 商品名
              %th 税抜価格
              %th カテゴリー
              %th ステータス
          - @products.each do |product|
            %tr
              %td= product.id
              %td= link_to product.name,admin_product_path(product)
              %td
                = product.price.to_s(:delimited)
                円
              %td= product.category.name
              %td= product.is_active
              %td= link_to "Destroy", admin_product_path(product), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book"
  = link_to new_admin_product_path,class: "pull-right" do
    %i.fas.fa-plus-circle

app/views/admin/products/new.html.haml
=render "template/header_admin"
.top-index
  .container
    %h3.page-title
      商品新規登録
    = form_for(@product, url:admin_products_path) do |f|
      - if @product.errors.any?
        %h3
          = @product.errors.count
          eroor
        %ul
          - @product.errors.full_messages.each do |message|
            %li= message
      .row
        .col-lg-3
          %b 画像のプレビュー
          = f.file_field :image, class: 'img_field', style: 'display:none;'
          = attachment_image_tag @product, :image, fallback: 'no_image.jpg', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev'
        .col-lg-7.offset-lg-1
          .row
            .col-lg-2
              %b 商品名　　
            .col-lg-10
              = f.text_field :name, {autocomplete: "off", class: "product-form"}
              円
          .row
            .col-lg-2
              %b 商品説明　
            .col-lg-10
              = f.text_area :introduction, autocomplete: "off",rows:"8", style:"width:300px"
          .row
            .col-lg-2
              %b ジャンル　
            .col-lg-10
          .row
            .col-lg-2
              %b 税込価格　
            .col-lg-10
              = f.text_field :price, {autocomplete: "off" , class: "product-form"}
              円
          .row
            .col-lg-2
              %b
                販売
                %br>/
                ステータス
            .col-lg-10
              = f.select :is_active, Product.is_actives.keys, |
              include_blank: "-- 選択してください --"               |
          .row
            .col-lg-4
            .col-lg-7
              = f.submit "新規登録", class:"btn btn-primary", style:"padding: 10px 30px;"

app/views/admin/products/show.html.haml
=render "template/header_admin"
.product-img-page
  .container
    %h3.page-title
      商品詳細
    .row
      .col-lg-12
        = attachment_image_tag @product, :image, fallback: "no_image.jpg",class: "product-image"
    .row
      .col-lg-1
      .col-lg-2
        %b 商品名
      .col-lg-8
        = @product.name
    .row
      .col-lg-1
      .col-lg-2
        %b 商品説明
      .col-lg-8
        = @product.introduction
    .row
      .col-lg-1
      .col-lg-2
        %b カテゴリー名
      .col-lg-8
        = @product.category.name
    .row
      .col-lg-1
      .col-lg-2
        %b 税込価格(税抜価格)
      .col-lg-8
        = @tax_price.to_s(:delimited)
        (#{@product.price})&#x5186;
    .row
      .col-lg-1
      .col-lg-2
        %b 販売ステータス
      .col-lg-8
        = @product.is_active
    .row
      .action-bottons
        = link_to "編集する",edit_admin_product_path(@product), class: "btn btn-primary bottom"

app/views/products/index.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
      
.container
  .row
    .col-lg-12
      %h3.top-product-title
        = @index_title
        一覧
        %span{:style => "font-size: 15px"}
          / 2個目のeach文で表示される予定のデータ数をカウントして表示
          - @sum = 0
          - @products.each do |product|
            - if product.category.is_active == "有効"
              - @sum += 1
          (全#{@sum.to_i}件)
      .products
        - @sum = 0
        - @products.each do |product|
          - if product.category.is_active == "有効"
            .product-content
              / 4つごとに折り返し
              .product-block
                = link_to product_path(product) do
                  = attachment_image_tag product, :image, format:"jpg",fallback:"no_image.jpg", class:"product-images"
                %p= product.name
                %p
                  ￥#{product.price.to_s(:delimited)}円
                  - @sum += 1
        .ranking__menu
          %p.ranking__menu__title
            RANKING

= render "template/footer"

app/views/products/show.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
.product-image-page
  .container
    .row
      .col-lg-5
        = attachment_image_tag @product, :image, fallback: "no_image.jpg",class: "product-show-image"

      .col-lg-7.product__title
        = @product.name

      .col-lg-7
        %p.product__title__price
          ¥
          = @tax_price.to_s(:delimited)
          %span.product-price
            税込

      .col-lg-7
        = form_for(@cart_item , url: user_cart_items_path, method: :post) do |f|
          .field
            - if user_signed_in?
              = f.hidden_field :product_id, value: @product.id
              = f.submit "カートに入れる", class: "btn btn-primary bottom"

      .col-lg-7
        = link_to "♡ お気に入りに追加",root_path, class: "btn btn-default "

      .col-lg-7.product__title__price__introduction
        = @product.introduction